name: build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore
      - name: Install tools
        run: dotnet tool restore
      - name: Paket install
        run: dotnet paket install
      - name: Build
        run: dotnet publish --configuration Release --no-restore --output ./output
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: active-game-night
          path: ./output # or path/to/artifact       
