name: Deploy

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Deploy to environment (test or prod)'
        required: true
        default: 'test'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install tools
        run: dotnet tool restore
      - name: Paket install
        run: dotnet paket install

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: active-game-night
          path: ./output
          
      - name: Deploy
        run: dotnet run --project -- environment=${{ github.event.inputs.Environment }}
        env:
          AGN_AZURE_APPID: ${{ secrets.AGN_AZURE_APPID }}
          AGN_AZURE_SECRET: ${{ secrets.AGN_AZURE_SECRET }}
          AGN_AZURE_TENANT: ${{ secrets.AGN_AZURE_TENANT }}

